global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api.schedulemanagement.site:8082']

  - job_name: 'kafka'
    static_configs:
      - targets: ['api.schedulemanagement.site:9308']

  - job_name: 'redis'
    static_configs:
      - targets: ['api.schedulemanagement.site:9121']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['api.schedulemanagement.site:9100']
