spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: roots
    url: jdbc:mariadb://localhost:3309/schedule?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create