spring:
  #spring gmail
  mail:
    host: smtp.gmail.com
    port: 587
    username: well414965@gmail.com
    password: fgow oooa brng gdoq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000