spring:
  mail:
    host: ${MAIL_TEST_HOST}
    port: ${MAIL_TEST_PORT}
    username: ${MAIL_TEST_USERNAME}
    password: ${MAIL_TEST_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000