server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://monitor.schedulemanagement.site/loki/api/v1/push

scrape_configs:
  - job_name: schedule-backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: schedule-backend
          __path__: /var/log/schedule-backend/*.log

  - job_name: kafka
    static_configs:
      - targets:
          - localhost
        labels:
          job: kafka
          __path__: /var/log/kafka/*.log

  - job_name: redis
    static_configs:
      - targets:
          - localhost
        labels:
          job: redis
          __path__: /var/log/redis/*.log
