name: Deploy to EC2 via SSH

on:
  workflow_run:
    workflows: ["Schedule Project CI with Compose"]  # CI yml의 name값
    types:
      - completed
    branches: 
      - main # main에 merge가 되었을때 cd가 작동

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # CI 성공했을때만
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            
            # 3. 최신 이미지 Pull 및 재기동
            # 파일 이름이 docker-compose.dev.yml인지 다시 한번 확인해봐!
            docker compose -f docker-compose.dev.yml pull
            docker compose -f docker-compose.dev.yml up -d --remove-orphans

            # 4. 정리 작업 (프리티어 용량 확보용)
            docker image prune -f
            sudo journalctl --vacuum-time=2d